CREATE TYPE "BookOfYearDuelPhase" AS ENUM ('MONTH_PAIR', 'SEMIFINAL');

CREATE TABLE "BookOfYearMonthlySelection" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "year" INTEGER NOT NULL, "month" INTEGER NOT NULL, "bookId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "BookOfYearMonthlySelection_pkey" PRIMARY KEY ("id"), CONSTRAINT "BookOfYearMonthlySelection_month_check" CHECK ("month" BETWEEN 1 AND 12), CONSTRAINT "BookOfYearMonthlySelection_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "BookOfYearMonthlySelection_bookId_fkey" FOREIGN KEY ("bookId") REFERENCES "Book"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "BookOfYearDuelWinner" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "year" INTEGER NOT NULL, "phase" "BookOfYearDuelPhase" NOT NULL, "position" INTEGER NOT NULL, "bookId" TEXT NOT NULL, "automatic" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "BookOfYearDuelWinner_pkey" PRIMARY KEY ("id"), CONSTRAINT "BookOfYearDuelWinner_position_check" CHECK ("position" BETWEEN 1 AND 6), CONSTRAINT "BookOfYearDuelWinner_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "BookOfYearDuelWinner_bookId_fkey" FOREIGN KEY ("bookId") REFERENCES "Book"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "BookOfYearFinalist" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "year" INTEGER NOT NULL, "position" INTEGER NOT NULL, "bookId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "BookOfYearFinalist_pkey" PRIMARY KEY ("id"), CONSTRAINT "BookOfYearFinalist_position_check" CHECK ("position" BETWEEN 1 AND 3), CONSTRAINT "BookOfYearFinalist_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "BookOfYearFinalist_bookId_fkey" FOREIGN KEY ("bookId") REFERENCES "Book"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "BookOfYearWinner" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "year" INTEGER NOT NULL, "bookId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "BookOfYearWinner_pkey" PRIMARY KEY ("id"), CONSTRAINT "BookOfYearWinner_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "BookOfYearWinner_bookId_fkey" FOREIGN KEY ("bookId") REFERENCES "Book"("id") ON DELETE CASCADE ON UPDATE CASCADE);

CREATE UNIQUE INDEX "BookOfYearMonthlySelection_userId_year_month_key" ON "BookOfYearMonthlySelection"("userId", "year", "month");
CREATE INDEX "BookOfYearMonthlySelection_userId_year_idx" ON "BookOfYearMonthlySelection"("userId", "year"); CREATE INDEX "BookOfYearMonthlySelection_bookId_idx" ON "BookOfYearMonthlySelection"("bookId");
CREATE UNIQUE INDEX "BookOfYearDuelWinner_userId_year_phase_position_key" ON "BookOfYearDuelWinner"("userId", "year", "phase", "position");
CREATE INDEX "BookOfYearDuelWinner_userId_year_phase_idx" ON "BookOfYearDuelWinner"("userId", "year", "phase"); CREATE INDEX "BookOfYearDuelWinner_bookId_idx" ON "BookOfYearDuelWinner"("bookId");
CREATE UNIQUE INDEX "BookOfYearFinalist_userId_year_position_key" ON "BookOfYearFinalist"("userId", "year", "position");
CREATE INDEX "BookOfYearFinalist_userId_year_idx" ON "BookOfYearFinalist"("userId", "year"); CREATE INDEX "BookOfYearFinalist_bookId_idx" ON "BookOfYearFinalist"("bookId");
CREATE UNIQUE INDEX "BookOfYearWinner_userId_year_key" ON "BookOfYearWinner"("userId", "year"); CREATE INDEX "BookOfYearWinner_bookId_idx" ON "BookOfYearWinner"("bookId");
