ALTER TYPE "ReactionType"
ADD VALUE IF NOT EXISTS 'THUMBS_UP';
ALTER TYPE "ReactionType"
ADD VALUE IF NOT EXISTS 'CRY';
ALTER TYPE "ReactionType"
ADD VALUE IF NOT EXISTS 'WOW';
ALTER TYPE "ReactionType"
ADD VALUE IF NOT EXISTS 'SWEAR';
ALTER TYPE "ReactionType"
ADD VALUE IF NOT EXISTS 'CLAP';